//If want to ignore specific folder to be as route , just wrap folder name in () [like (auth)]. The route [auth/login] will not work [/login] will work even though we have placed login & register inside auth folder.

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
